#!/bin/python3

import os
import sys

#
# Complete the connectingTowns function below.
#
def connectingTowns(routes):
    #
    # Write your code here.
    #
    a=1
    for i in routes:
        a=a*int(i)
        a%=1234567 
    return a
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        routes = list(map(int, input().rstrip().split()))

        result = connectingTowns(routes)

        fptr.write(str(result) + '\n')

    fptr.close()
